version: '3.8'
services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    restart: always

  app:
    build: './nodeapp'
    environment:
      PORT: 3000
    ports:
      - 8080:3000
    volumes:
      - ./nodeapp:/app
      - app_data:/app/node_modules
    depends_on:
      - mongo

volumes:
  mongo_data:
  mongo_config:
  app_data: